version: "3.6"

services:
  zomboid-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - "BIND_IP=0.0.0.0"
      - "GAME_VERSION=public"
      - "QUERY_PORT=16261"
      - "SERVER_NAME=ZomboidServer"
      - "ADMIN_USERNAME=superuser"
      - "ADMIN_PASSWORD=changeme"
      - "USE_STEAM=true"
      - "STEAM_VAC=true"
    ports:
      - target: 8766
        published: 8766
        protocol: udp
      - target: 16261
        published: 16261
        protocol: udp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
    cap_drop:
      - ALL
